import {
  FaAws,
  FaBroadcastTower,
  FaChartLine,
  FaCode,
  FaDatabase,
  FaDocker,
  FaEye,
  FaJs,
  FaLaravel,
  FaMicrochip,
  FaPython,
  FaReact,
  FaServer,
  FaTheaterMasks,
  FaVideo,
  FaWindowMaximize,
} from "react-icons/fa";
import {
  SiArduino,
  SiCplusplus,
  SiEspressif,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGooglemaps,
  SiJenkins,
  SiLaragon,
  SiMeilisearch,
  SiMui,
  SiMysql,
  SiRaspberrypi,
  SiRedis,
  SiRedux,
  SiSelenium,
  SiSqlalchemy,
  SiSqlite,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
} from "react-icons/si";

export const tags = {
  Alembic: { icon: <FaDatabase color="#6E7B8B" />, color: "#6E7B8B" },
  Arduino: { icon: <SiArduino color="#00979D" />, color: "#00979D" },
  AWS: { icon: <FaAws color="#FF9900" />, color: "#FF9900" },
  "C++": { icon: <SiCplusplus color="#00599C" />, color: "#00599C" },
  Caddy: { icon: <FaServer color="#00B3C4" />, color: "#00B3C4" },
  Docker: { icon: <FaDocker color="#0db7ed" />, color: "#0db7ed" },
  ESP32: { icon: <SiEspressif color="#E7352C" />, color: "#E7352C" },
  FastAPI: { icon: <SiFastapi color="#05998B" />, color: "#05998B" },
  Firebase: { icon: <SiFirebase color="#FFCA28" />, color: "#FFCA28" },
  Flask: { icon: <SiFlask color="#000000" />, color: "#000000" },
  Flutter: { icon: <SiFlutter color="#02569B" />, color: "#02569B" },
  GoogleMaps: { icon: <SiGooglemaps color="#4285F4" />, color: "#4285F4" },
  Jaeger: { icon: <FaChartLine color="#67CF00" />, color: "#67CF00" },
  Javascript: { icon: <FaJs color="#F7DF1E" />, color: "#F7DF1E" },
  Jenkins: { icon: <SiJenkins color="#D24939" />, color: "#D24939" },
  Laragon: { icon: <SiLaragon color="#0E83CD" />, color: "#0E83CD" },
  Laravel: { icon: <FaLaravel color="#FF2D20" />, color: "#FF2D20" },
  LoRa: { icon: <FaBroadcastTower color="#E8590C" />, color: "#E8590C" },
  MediaMTX: { icon: <FaVideo color="#00A0C6" />, color: "#00A0C6" },
  Meilisearch: { icon: <SiMeilisearch color="#FF5E8A" />, color: "#FF5E8A" },
  MQTT: { icon: <FaMicrochip color="#7A1FA2" />, color: "#7A1FA2" },
  MUI: { icon: <SiMui color="#007FFF" />, color: "#007FFF" },
  MySQL: { icon: <SiMysql color="#4479A1" />, color: "#4479A1" },
  Playwright: { icon: <FaTheaterMasks color="#2EAD33" />, color: "#2EAD33" },
  Python: { icon: <FaPython color="#3776AB" />, color: "#3776AB" },
  RaspberryPi: { icon: <SiRaspberrypi color="#C51A4A" />, color: "#C51A4A" },
  React: { icon: <FaReact color="#61DAFB" />, color: "#61DAFB" },
  ReactAdmin: { icon: <FaReact color="#61DAFB" />, color: "#61DAFB" },
  Redis: { icon: <SiRedis color="#DC382D" />, color: "#DC382D" },
  Redux: { icon: <SiRedux color="#764ABC" />, color: "#764ABC" },
  Riverpod: { icon: <FaCode color="#0080C6" />, color: "#0080C6" },
  Selenium: { icon: <SiSelenium color="#43B02A" />, color: "#43B02A" },
  SQLModel: { icon: <SiSqlalchemy color="#D21F3C" />, color: "#D21F3C" },
  SQLite: { icon: <SiSqlite color="#003B57" />, color: "#003B57" },
  Tailwind: { icon: <SiTailwindcss color="#06B6D4" />, color: "#06B6D4" },
  TensorFlow: { icon: <SiTensorflow color="#FF6F00" />, color: "#FF6F00" },
  Tkinter: { icon: <FaWindowMaximize color="#3776AB" />, color: "#3776AB" },
  TypeScript: { icon: <SiTypescript color="#3178C6" />, color: "#3178C6" },
  YOLO: { icon: <FaEye color="#FFCC00" />, color: "#FFCC00" },
} as const;
