import {
  FaAws,
  FaDocker,
  FaJs,
  FaLaravel,
  FaPython,
  FaReact,
  FaTheaterMasks,
  FaWindowMaximize,
} from "react-icons/fa";
import {
  SiArduino,
  SiDjango,
  SiFlutter,
  SiFastapi,
  SiFlask,
  SiJenkins,
  SiLaragon,
  SiMui,
  SiMysql,
  SiSelenium,
  SiRaspberrypi,
  SiRedis,
  SiTypescript,
  SiTailwindcss,
} from "react-icons/si";

export const tags = {
  Arduino: { icon: <SiArduino color="#00979D" />, color: "#00979D" },
  AWS: { icon: <FaAws color="#FF9900" />, color: "#FF9900" },
  Django: { icon: <SiDjango color="#092E20" />, color: "#092E20" },
  Docker: { icon: <FaDocker color="#0db7ed" />, color: "#0db7ed" },
  FastAPI: { icon: <SiFastapi color="#05998B" />, color: "#05998B" },
  Flask: { icon: <SiFlask color="#000000" />, color: "#000000" },
  Flutter: { icon: <SiFlutter color="#02569B" />, color: "#02569B" },
  Javascript: { icon: <FaJs color="#F7DF1E" />, color: "#F7DF1E" },
  Jenkins: { icon: <SiJenkins color="#D24939" />, color: "#D24939" },
  Laragon: { icon: <SiLaragon color="#0E83CD" />, color: "#0E83CD" },
  Laravel: { icon: <FaLaravel color="#FF2D20" />, color: "#FF2D20" },
  MUI: { icon: <SiMui color="#007FFF" />, color: "#007FFF" },
  MySQL: { icon: <SiMysql color="#4479A1" />, color: "#4479A1" },
  Playwright: { icon: <FaTheaterMasks color="#2EAD33" />, color: "#2EAD33" },
  Python: { icon: <FaPython color="#3776AB" />, color: "#3776AB" },
  RaspberryPi: { icon: <SiRaspberrypi color="#C51A4A" />, color: "#C51A4A" },
  React: { icon: <FaReact color="#61DAFB" />, color: "#61DAFB" },
  ReactAdmin: { icon: <FaReact color="#61DAFB" />, color: "#61DAFB" },
  Redis: { icon: <SiRedis color="#DC382D" />, color: "#DC382D" },
  Selenium: { icon: <SiSelenium color="#43B02A" />, color: "#43B02A" },
  Tailwind: { icon: <SiTailwindcss color="#06B6D4" />, color: "#06B6D4" },
  Tkinter: { icon: <FaWindowMaximize color="#3776AB" />, color: "#3776AB" },
  TypeScript: { icon: <SiTypescript color="#3178C6" />, color: "#3178C6" },
} as const;
